### ISSUE TITLE
Fails to build with gcc 9

### ISSUE THREAD

**Issue by opoplawski** [dmtcp/dmtcp#730] opened 2019-02-24 04:51 UTC
Trying to build with GCC 9 for Fedora Rawhide.  I get:
```
BUILDSTDERR: shareddata.cpp: In function 'bool dmtcp::SharedData::getCkptLeaderForFile(dev_t, ino_t, void*)':
BUILDSTDERR: shareddata.cpp:597:63: error: cannot bind packed field 'sharedDataHeader->dmtcp::SharedData::Header::inodeConnIdMap[i]' to 'dmtcp::SharedData::InodeConnIdMap&'
BUILDSTDERR:   597 |       InodeConnIdMap& map = sharedDataHeader->inodeConnIdMap[i];
BUILDSTDERR:       |                             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
```
There are also a number of warnings like:
```
BUILDSTDERR: shareddata.cpp: In function 'dmtcp::string dmtcp::SharedData::coordHost()':
BUILDSTDERR: shareddata.cpp:204:33: warning: taking address of packed member of 'dmtcp::SharedData::Header' may result in an unaligned pointer value [-Waddress-of-packed-member]
BUILDSTDERR:   204 |     (const struct sockaddr_in*) &sharedDataHeader->coordInfo.addr;
BUILDSTDERR:       |                                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

**Comment by opoplawski** [comment] 2019-02-24 04:52
```
make display-build-env
DMTCP version: 2.5.2
Date built:    Sun Feb 24 04:48:37 UTC 2019
config.log:    ./configure --build=x86_64-redhat-linux-gnu --host=x86_64-redhat-linux-gnu --program-prefix= --disable-dependency-tracking --prefix=/usr --exec-prefix=/usr --bindir=/usr/bin --sbindir=/usr/sbin --sysconfdir=/etc --datadir=/usr/share --includedir=/usr/include --libdir=/usr/lib64 --libexecdir=/usr/libexec --localstatedir=/var --sharedstatedir=/var/lib --mandir=/usr/share/man --infodir=/usr/share/info --docdir=/usr/share/doc/dmtcp
Fedora release 31 (Rawhide)
Linux buildvm-05.phx2.fedoraproject.org 4.19.8-300.fc29.x86_64 #1 SMP Mon Dec 10 15:23:11 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
libc version: ldd (GNU libc) 2.29
Compiler:  gcc
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/libexec/gcc/x86_64-redhat-linux/9/lto-wrapper
OFFLOAD_TARGET_NAMES=nvptx-none
OFFLOAD_TARGET_DEFAULT=1
Target: x86_64-redhat-linux
Configured with: ../configure --enable-bootstrap --enable-languages=c,c++,fortran,objc,obj-c++,ada,go,d,lto --prefix=/usr --mandir=/usr/share/man --infodir=/usr/share/info --with-bugurl=http://bugzilla.redhat.com/bugzilla --enable-shared --enable-threads=posix --enable-checking=release --enable-multilib --with-system-zlib --enable-__cxa_atexit --disable-libunwind-exceptions --enable-gnu-unique-object --enable-linker-build-id --with-gcc-major-version-only --with-linker-hash-style=gnu --enable-plugin --enable-initfini-array --with-isl --enable-offload-targets=nvptx-none --without-cuda-driver --enable-gnu-indirect-function --enable-cet --with-tune=generic --with-arch_32=i686 --build=x86_64-redhat-linux
Thread model: posix
gcc version 9.0.1 20190209 (Red Hat 9.0.1-0.4) (GCC) 
CFLAGS: -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fexceptions -fstack-protector-strong -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection
CXXFLAGS: -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fexceptions -fstack-protector-strong -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection
CPPFLAGS: 
LDFLAGS: -Wl,-z,relro -Wl,--as-needed  -Wl,-z,now -specs=/usr/lib/rpm/redhat/redhat-hardened-ld
```

**Comment by loveshack** [comment] 2019-09-04 13:56
It's fixed in 2.6, for which I added a Fedora pull request.

**Comment by gc00** [comment] 2019-09-04 17:05
Confirmed.  DMTCP-2.6.0 supports gcc-9.  I am closing this issue.

@loveshack , Thanks for adding the Fedora pull request.  We would like to change the Fedora maintainer from @karya0 (who has less time now) to @pgrosu .  If you have a pointer on how to do this, that would be helpful.

**Closed by gc00** 2019-09-04 17:05 UTC

**Comment by opoplawski** [comment] 2019-09-04 18:35
@karya0 would go to https://src.fedoraproject.org/rpms/dmtcp/settings#usersgroups-tab and add @pgrosu - presuming that @pgrosu is already a Fedora maintainer.

**Comment by gc00** [comment] 2019-09-04 21:04
@pgrosu is not yet a Fedora maintainer.  What do we need to do to qualify @pgrosu as a Fedora maintainer for DMTCP?  Thanks.

**Comment by loveshack** [comment] 2019-09-05 09:30
> @pgrosu is not yet a Fedora maintainer.  What do we need to do to
> qualify @pgrosu as a Fedora maintainer for DMTCP?  Thanks.

The instructions are at
https://fedoraproject.org/wiki/Join_the_package_collection_maintainers
The difficult bit is getting sponsored.

I've lost track of current policy, but I think dmtcp is in danger of
falling out of Fedora, along with the EPEL versions which is all I
actually care about.  The source for recent releases is marked "dead"
due to build failures.

If Kapil could add me as an admin, I could keep it alive pending the
maintainer change.  I you want to check, my Fedora efforts are
https://src.fedoraproject.org/user/loveshack/projects and
https://copr.fedorainfracloud.org/coprs/loveshack/livhpc/ has unofficial
packages.  (Orion has build superpowers, but probably not time, which I
have a bit of now.)
